version: "3.11"

x-service-template: &service-template
  restart: always
  build:
    context: ./.
    dockerfile: ./docker/Dockerfile
  networks:
    - default
  volumes:
    - .:/code
  environment:
    - APP_PORT=${APP_PORT}

services:
  # FastAPI сервисы
  auth:
    <<: *service-template
    environment:
      - APP_SERVICE=auth
    entrypoint: ["sh", "./scripts/start_api.sh"]

  pixverse:
    <<: *service-template
    environment:
      - APP_SERVICE=pixverse
    entrypoint: ["sh", "./scripts/start_api.sh"]

  chatgpt:
    <<: *service-template
    environment:
      - APP_SERVICE=chatgpt
    entrypoint: ["sh", "./scripts/start_api.sh"]

  dashboard:
    <<: *service-template
    environment:
      - APP_SERVICE=dashboard
    entrypoint: ["sh", "./scripts/start_api.sh"]

  calories:
    <<: *service-template
    environment:
      - APP_SERVICE=calories
    entrypoint: ["sh", "./scripts/start_api.sh"]

  instagram:
    <<: *service-template
    environment:
      - APP_SERVICE=instagram
    entrypoint: ["sh", "./scripts/start_api.sh"]

  cosmetic:
    <<: *service-template
    environment:
      - APP_SERVICE=cosmetic
    entrypoint: ["sh", "./scripts/start_api.sh"]

  qwen:
    <<: *service-template
    environment:
      - APP_SERVICE=qwen
    entrypoint: ["sh", "./scripts/start_api.sh"]

  topmedia:
    <<: *service-template
    environment:
      - APP_SERVICE=topmedia
    entrypoint: ["sh", "./scripts/start_api.sh"]

  # Воркеры
  pixverse-account-worker:
    <<: *service-template
    environment:
      - TASK_APP=pixverse_account
    entrypoint: ["sh", "./scripts/start_job.sh"]

  pixverse-template-worker:
    <<: *service-template
    environment:
      - TASK_APP=pixverse_template
    entrypoint: ["sh", "./scripts/start_job.sh"]

  pixverse-style-worker:
    <<: *service-template
    environment:
      - TASK_APP=pixverse_style
    entrypoint: ["sh", "./scripts/start_job.sh"]

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/web.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth
      - pixverse
      - chatgpt
      - dashboard
      - calories
      - instagram
      - cosmetic
      - qwen
      - topmedia
    networks:
      - default

networks:
  default:
    driver: bridge
