version: "3.11"

x-service-template: &service-template
  restart: always
  build:
    context: ./.
    dockerfile: ./docker/Dockerfile
  networks:
      - default
  volumes:
    - .:/code
  environment:
    - APP_PORT=${APP_PORT}

services:
  auth:
    <<: *service-template
    ports:
      - 8001:${APP_PORT}
    environment:
      - APP_SERVICE=auth
    entrypoint: ["sh", "./scripts/start_api.sh"]
  pixverse:
    <<: *service-template
    ports:
      - 8002:${APP_PORT}
    environment:
      - APP_SERVICE=pixverse
    entrypoint: ["sh", "./scripts/start_api.sh"]

  chatgpt:
    <<: *service-template
    ports:
      - 8003:${APP_PORT}
    environment:
      - APP_SERVICE=chatgpt
    entrypoint: ["sh", "./scripts/start_api.sh"]
  
  dashboard:
    <<: *service-template
    ports:
      - 8004:${APP_PORT}
    environment:
      - APP_SERVICE=dashboard
    entrypoint: ["sh", "./scripts/start_api.sh"]

  pixverse-account-worker:
    <<: *service-template
    environment:
      - TASK_APP=pixverse_account
    entrypoint: ["sh", "./scripts/start_job.sh"]

  pixverse-template-worker:
    <<: *service-template
    environment:
      - TASK_APP=pixverse_template
    entrypoint: ["sh", "./scripts/start_job.sh"]

  pixverse-style-worker:
    <<: *service-template
    environment:
      - TASK_APP=pixverse_style
    entrypoint: ["sh", "./scripts/start_job.sh"]