version: "3.11"

x-service-template: &service-template
  restart: always
  build:
    context: ./.
    dockerfile: ./docker/Dockerfile
  networks:
      - default
  environment:
    - APP_PORT=${APP_PORT}

services:
  api:
    <<: *service-template
    ports:
      - 8001:${APP_PORT}
    environment:
      - APP_PROJECT=api