version: "3.11"

x-service-template: &service-template
  restart: always
  build:
    context: ./.
    dockerfile: ./docker/Dockerfile
  networks:
      - default
  volumes:
    - .:/code
  environment:
    - APP_PORT=${APP_PORT}

services:
  auth:
    <<: *service-template
    ports:
      - 8001:${APP_PORT}
    environment:
      - APP_SERVICE=auth
  pixverse:
    <<: *service-template
    ports:
      - 8002:${APP_PORT}
    environment:
      - APP_SERVICE=pixverse

  chatgpt:
    <<: *service-template
    ports:
      - 8003:${APP_PORT}
    environment:
      - APP_SERVICE=chatgpt
  
  dashboard:
    <<: *service-template
    ports:
      - 8003:${APP_PORT}
    environment:
      - APP_SERVICE=dashboard